$ErrorActionPreference = 'Stop'

$Version = '1.33'
$Revision = '1.33-delete-recreate-tests'
$Repo = $env:FHM_UPGRADE_REPO
if ([string]::IsNullOrWhiteSpace($Repo)) { $Repo = (Get-Location).ProviderPath }
$Repo = [IO.Path]::GetFullPath($Repo).TrimEnd('\')
$LogsDir = Join-Path $Repo 'logs'
New-Item -ItemType Directory -Path $LogsDir -Force | Out-Null
$Log = Join-Path $LogsDir 'upgrade.log'
$HadWarning = $false
$FailPhase = 'UNKNOWN'

$Utf8 = [Text.UTF8Encoding]::new($false)
[Console]::OutputEncoding = $Utf8
$OutputEncoding = $Utf8
try { & chcp.com 65001 *> $null } catch { }
[IO.File]::WriteAllText($Log, '', $Utf8)
function Write-Line([string]$Text,[ConsoleColor]$Color=[ConsoleColor]::Gray){[IO.File]::AppendAllText($Log,$Text+[Environment]::NewLine,$Utf8);Write-Host $Text -ForegroundColor $Color}
function Info([string]$Text){Write-Line $Text Gray};function Warn([string]$Text){$script:HadWarning=$true;Write-Line('WARNING: '+$Text) Yellow};function Fail([string]$Phase,[string]$Text){$script:FailPhase=$Phase;Write-Line('ERROR: '+$Text) Red;throw[InvalidOperationException]::new($Text)}
function Run-Native{param([string]$Phase,[string]$Exe,[string[]]$ArgumentList,[switch]$AllowFailure);$saved=$ErrorActionPreference;try{$ErrorActionPreference='Continue';&$Exe @ArgumentList 2>&1|ForEach-Object{$line=[string]$_;if($line-match'(?i)\b(error|failed|fatal error)\b|\berror\s+(C|LNK)\d+|MSB\d+.*\berror\b'){Write-Line $line Red}elseif($line-match'(?i)\bwarning\b'){Write-Line $line Yellow}else{Write-Line $line Gray}};$rc=$LASTEXITCODE}finally{$ErrorActionPreference=$saved};if($rc-ne0-and-not$AllowFailure){Fail $Phase("$Exe failed with exit code $rc")};return$rc}
function Is-ProcessRunning([string[]]$Names){foreach($n in $Names){if(Get-Process -Name $n -ErrorAction SilentlyContinue){return$true}};return$false}
function Get-RegValue([string]$Path,[string]$Name){try{return(Get-ItemProperty -Path $Path -Name $Name -ErrorAction Stop).$Name}catch{return$null}}
function Resolve-CMake{$cmd=Get-Command cmake.exe -ErrorAction SilentlyContinue;if($cmd){return$cmd.Source};$vswhere=Join-Path ${env:ProgramFiles(x86)}'Microsoft Visual Studio\Installer\vswhere.exe';if(Test-Path $vswhere){$found=&$vswhere -latest -products '*' -requires Microsoft.VisualStudio.Component.VC.CMake.Project -find 'Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe'|Select-Object -First 1;if($found){return[string]$found}};return$null}
function Resolve-TC{$tcPath=$env:COMMANDER_PATH;$tcIni=$env:COMMANDER_INI;$keys=@('HKCU:\Software\Ghisler\Total Commander','HKLM:\Software\Ghisler\Total Commander','HKLM:\Software\Wow6432Node\Ghisler\Total Commander');if(-not$tcPath){foreach($k in $keys){$v=Get-RegValue $k'InstallDir';if($v){$tcPath=$v;break}}};if(-not$tcIni){foreach($k in $keys){$v=Get-RegValue $k'IniFileName';if($v){$tcIni=$v;break}}};$tcExe=$null;if($tcPath){foreach($name in @('TOTALCMD64.EXE','TOTALCMD.EXE')){$p=Join-Path $tcPath $name;if(Test-Path $p){$tcExe=$p;break}}};$plugin=$null;if($tcIni-and(Test-Path $tcIni)){foreach($line in Get-Content -LiteralPath $tcIni){if($line-match'FolderHeatMap\.wdx64'-and$line-match'='){$plugin=($line-split'=',2)[1].Trim('"');break}}};$settings=if($tcIni){Join-Path(Split-Path -Parent $tcIni)'FolderHeatMap.ini'}else{$null};[pscustomobject]@{Path=$tcPath;Ini=$tcIni;Exe=$tcExe;Plugin=$plugin;Settings=$settings}}
function Stop-TotalCommanderForDeploy{param([string]$Reason='deployment');$names=@('TOTALCMD64','TOTALCMD');$running=@(Get-Process -Name $names -ErrorAction SilentlyContinue);if(-not$running){return};Warn("Total Commander is running during $Reason; stopping it.");$running|Stop-Process -Force -ErrorAction SilentlyContinue;Start-Sleep -Milliseconds 500;if(Is-ProcessRunning $names){Fail'DEPLOY''Total Commander keeps running/restarting.'}}
function Stop-EngineForDeploy{param([string]$Reason='deployment');$running=@(Get-Process -Name'FolderHeatMapEngine' -ErrorAction SilentlyContinue);if(-not$running){return};Warn("FolderHeatMapEngine is running during $Reason; stopping it.");$running|Stop-Process -Force -ErrorAction SilentlyContinue;Start-Sleep -Milliseconds 500;if(Is-ProcessRunning @('FolderHeatMapEngine')){Fail'DEPLOY''FolderHeatMapEngine keeps running/restarting.'}}
function Copy-FileWithRetry{param([string]$Source,[string]$Destination,[switch]$GuardTotalCommander,[switch]$GuardEngine);$parent=Split-Path -Parent $Destination;if($parent){New-Item -ItemType Directory -Path $parent -Force|Out-Null};for($i=1;$i-le30;$i++){if($GuardTotalCommander){Stop-TotalCommanderForDeploy "copy attempt $i"};if($GuardEngine){Stop-EngineForDeploy "copy attempt $i"};try{Copy-Item -LiteralPath $Source -Destination $Destination -Force -ErrorAction Stop;return}catch{if($i-eq30){Fail'DEPLOY'("Could not replace '$Destination': $($_.Exception.Message)")};Start-Sleep -Seconds 1}}}
try{
 Set-Location $Repo;Info'============================================================';Info'FolderHeatMap upgrade diagnostic log';Info("Version:    $Revision");Info('Started:    '+[DateTime]::Now.ToString('dd.MM.yyyy HH:mm:ss.fff'));Info("Repository: $Repo");Info'============================================================'
 $FailPhase='SELF-UPDATE';Run-Native $FailPhase'git.exe'@('fetch','origin')|Out-Null;$currentBranch=(&git branch --show-current).Trim();if($currentBranch-ne'devel'){Run-Native $FailPhase'git.exe'@('switch','devel')|Out-Null};&git diff --quiet --ignore-submodules -- . ':(exclude)upgrade.cmd' ':(exclude)upgrade.ps1';$dirty=($LASTEXITCODE-ne0);if($dirty){Warn'Local tracked changes detected; stashing before update.';Run-Native $FailPhase'git.exe'@('stash','push','-m','FolderHeatMap automatic pre-upgrade stash')|Out-Null};Run-Native $FailPhase'git.exe'@('reset','--hard','origin/devel')|Out-Null;$head=(&git rev-parse HEAD).Trim();$remote=(&git rev-parse origin/devel).Trim();if($head-ne$remote){Fail $FailPhase'Local HEAD differs from origin/devel.'};Info("[GIT] Build commit: $head")
 $tc=Resolve-TC;$cmake=Resolve-CMake;if(-not$cmake){Fail'DEPENDENCIES''CMake/Visual Studio Build Tools not found.'};if(-not(Test-Path "$Repo\vendor\sqlite\sqlite3.c")){Fail'DEPENDENCIES''SQLite source is missing; use an existing configured checkout.'}
 $tcWasRunning=Is-ProcessRunning @('TOTALCMD64','TOTALCMD');Info'[1/7] Stopping runtime...';Stop-TotalCommanderForDeploy'upgrade';Stop-EngineForDeploy'upgrade'
 $FailPhase='CONFIGURATION';Info'[2/7] Configuring repository-local logging path...';if($tc.Settings-and(Test-Path "$Repo\configure_logging_path.ps1")){&powershell.exe -NoProfile -ExecutionPolicy Bypass -File "$Repo\configure_logging_path.ps1" -SettingsIni $tc.Settings -RepositoryRoot $Repo|Out-Null}
 Info'[3/7] Preparing build...';$build=Join-Path $Repo'build';if(Test-Path $build){Remove-Item $build -Recurse -Force};Info'[4/7] Configuring x64 Release build...';Run-Native'CMAKE-CONFIGURE'$cmake@('-S','.','-B','build','-A','x64')|Out-Null;Info'[5/7] Building FolderHeatMap 1.33 and tools...';Run-Native'BUILD'$cmake@('--build','build','--config','Release','--target','FolderHeatMap','FolderHeatMapEngine','FolderHeatMapConfig','FolderHeatMapReset')|Out-Null
 $artifacts=@('FolderHeatMap.wdx64','FolderHeatMapEngine.exe','FolderHeatMapConfig.exe','FolderHeatMapReset.exe');foreach($f in $artifacts){if(-not(Test-Path(Join-Path "$build\Release"$f))){Fail'BUILD'"$f is missing after build."}}
 Info'[6/7] Preparing isolated package staging...';$package=Join-Path $build'package';New-Item -ItemType Directory -Path $package -Force|Out-Null;foreach($f in $artifacts){Copy-Item(Join-Path "$build\Release"$f)(Join-Path $package $f)-Force};foreach($f in @('configure.cmd','README.md','TESTING.md','test.cmd','test.ps1')){if(Test-Path(Join-Path $Repo $f)){Copy-Item(Join-Path $Repo $f)(Join-Path $package $f)-Force}}
 Info'[7/7] Deploying staged package...';$dist=Join-Path $Repo'dist';New-Item -ItemType Directory -Path $dist -Force|Out-Null;foreach($f in $artifacts){Copy-FileWithRetry(Join-Path $package $f)(Join-Path $dist $f)-GuardTotalCommander:($f-eq'FolderHeatMap.wdx64')-GuardEngine:($f-eq'FolderHeatMapEngine.exe')};foreach($f in @('configure.cmd','README.md','TESTING.md','test.cmd','test.ps1')){if(Test-Path(Join-Path $package $f)){Copy-FileWithRetry(Join-Path $package $f)(Join-Path $dist $f)}}
 if($tc.Plugin){$pluginFull=[IO.Path]::GetFullPath($tc.Plugin);$distPlugin=[IO.Path]::GetFullPath((Join-Path $dist'FolderHeatMap.wdx64'));if(-not$pluginFull.Equals($distPlugin,[StringComparison]::OrdinalIgnoreCase)){$pluginDir=Split-Path -Parent $pluginFull;Copy-FileWithRetry(Join-Path $package'FolderHeatMap.wdx64')$pluginFull -GuardTotalCommander;Copy-FileWithRetry(Join-Path $package'FolderHeatMapEngine.exe')(Join-Path $pluginDir'FolderHeatMapEngine.exe')-GuardEngine}}
 $launcher=Join-Path $Repo'start_engine.ps1';if(Test-Path $launcher){Start-Process powershell.exe -ArgumentList @('-NoProfile','-ExecutionPolicy','Bypass','-File',$launcher)-WindowStyle Hidden|Out-Null};if($tcWasRunning-and$tc.Exe){Start-Process -FilePath $tc.Exe|Out-Null};Write-Line'';Write-Line"SUCCESS - FolderHeatMap $Version installed." Green;Write-Line'STATUS: SUCCESS - phase=COMPLETE' Green;exit 0
}catch{if($FailPhase-eq'UNKNOWN'){$FailPhase='UNEXPECTED'};Write-Line('ERROR: '+$_.Exception.Message) Red;Write-Line("STATUS: FAILED - phase=$FailPhase") Red;exit 1}
